export const MOCK_ALLIES = [
    {
        id: 'ally-001',
        name: 'Carnes Don Julio',
        category: 'Carnicería',
        specialty: 'Cortes Premium',
        location: 'Cali, Valle del Cauca',
        image_url: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=800&q=80',
        description: 'Cortes selectos madurados y frescos para tus asados de fin de semana.',
        benefit: '15% de descuento en Punta de Anca',
        phone: '310 123 4567',
        address: 'Av. Pasoancho # 50-20',
        discount_info: '15% de descuento en cortes premium',
    },
    {
        id: 'ally-002',
        name: 'La Parrilla de Pepe',
        category: 'Restaurante',
        specialty: 'Parrilla & Barril',
        location: 'Cali, Valle del Cauca',
        image_url: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80',
        description: 'Expertos en cocción lenta al barril. Chicharrón ahumado inigualable.',
        benefit: '2x1 los jueves en platos de cerdo',
        phone: '315 987 6543',
        address: 'Granada Calle 9 # 12-45',
        discount_info: '2x1 los jueves en platos de cerdo',
    },
    {
        id: 'ally-003',
        name: 'El Fogón de la Abuela',
        category: 'Restaurante',
        specialty: 'Comida Típica',
        location: 'Cali, Valle del Cauca',
        image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
        description: 'Sabor tradicional con ingredientes del campo directo a tu mesa.',
        benefit: 'Postre gratis por consumo > $50k',
        phone: '312 456 7890',
        address: 'San Antonio Cra 4 # 2-10',
        discount_info: '10% en platos con cerdo',
    },
    {
        id: 'ally-004',
        name: 'SuperCarnes Express',
        category: 'Distribuidor',
        specialty: 'Venta al Por Mayor',
        location: 'Medellín, Antioquia',
        image_url: 'https://images.unsplash.com/photo-1615937651188-4b92cd38052e?auto=format&fit=crop&w=800&q=80',
        description: 'Abastecemos tu negocio con la mejor carne de cerdo de la región.',
        benefit: 'Envío gratis en pedidos mayoristas',
        phone: '300 555 1234',
        address: 'Centro, Calle 50 # 40-20',
        discount_info: 'Entrega gratuita en Medellín',
    },
    {
        id: 'ally-005',
        name: 'Huellitas Felices',
        category: 'Petshop',
        specialty: 'Alimentos y Spa',
        location: 'Bogotá, Cundinamarca',
        image_url: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=800&q=80',
        description: 'Todo para consentir a tu peludo. Baño, peluquería y juguetes.',
        benefit: '10% en Baño y Peluquería',
        phone: '312 456 7890',
        address: 'Av. Principal # 45-12',
        discount_info: '10% en Baño y Peluquería',
    },
    {
        id: 'ally-006',
        name: 'El Barbero',
        category: 'Barbería',
        specialty: 'Cortes Clásicos',
        location: 'Cali, Valle del Cauca',
        image_url: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=800&q=80',
        description: 'Estilo y tradición. Afeitado con toalla caliente y los mejores cortes.',
        benefit: '2x1 en corte de cabello y barba',
        phone: '315 789 1234',
        address: 'Calle 10 # 20-30',
        discount_info: '2x1 en corte de cabello y barba',
    }
];

export const MOCK_MISSIONS = [
    {
        id: '1',
        title: 'Primeros Pasos',
        description: 'Completa tu perfil de usuario',
        points: 500,
        completed: false,
    },
    {
        id: '2',
        title: 'Inversionista Novato',
        description: 'Realiza tu primera inversión en un Piggy',
        points: 1000,
        completed: false,
    },
    {
        id: '3',
        title: 'Líder de Manada',
        description: 'Invita a 3 amigos a unirse a la app',
        points: 2000,
        completed: false,
    },
];

export const MOCK_MARKETPLACE = [
    {
        id: 'item-001',
        name: 'Piggy Estándar',
        description: 'Comienza tu camino en el agro. Un cerdo de raza clásica con rendimiento sólido.',
        price: 1000000,
        roi: '+15%', // Base ROI representation
        image_url: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=800&q=80',
    },
    {
        id: 'item-002',
        name: 'Piggy Premium',
        description: 'Cerdo de raza premium con alimentación especial. Bono de +1% adicional.',
        price: 1200000,
        roi: '+16%',
        image_url: 'https://images.unsplash.com/photo-1604848698030-c434ba08ece1?auto=format&fit=crop&w=800&q=80',
    },
    {
        id: 'item-003',
        name: 'Piggy Elite',
        description: 'Cerdo élite con genética superior y cuidado personalizado. Bono de +2% adicional.',
        price: 1500000,
        roi: '+17%',
        image_url: 'https://images.unsplash.com/photo-1595133614945-896898b671a5?auto=format&fit=crop&w=800&q=80',
    },
];
