name: Deploy Migrations to Supabase

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # Agregamos el paso de LINK explícito
      - name: Link Supabase Project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --password ${{ secrets.SUPABASE_DB_PASSWORD }}

      - name: Deploy Migrations
        run: supabase db push --include-all --password ${{ secrets.SUPABASE_DB_PASSWORD }}
